### ISSUE TITLE
Error Handling broken?

### ISSUE THREAD

**Issue by khare-ashwini** [fluidsonic/co-feedparser#1]
I posted a [question](https://stackoverflow.com/questions/38025362/javascript-generator-catch-error) on stackoverflow about catching exceptions using this library having some troubles. Do you know what would be a possible solution for this?

**Comment by fluidsonic** [comment]
Thank you for reporting this issue.
Looks like the underlying `feedparser` package wasn't handling errors properly at version 0.16.5.

I've just published version 1.1.4 of `co-feedparser` which uses `feedparser` 1.1.4.

You can properly catch errors now :)
